In [27]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores_df.index.name = '學號'
scores_df.columns.name = '科目'

In [28]:
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
rank_series = sum_series.rank(method='min', ascending=False)
scores_df['總分'] = sum_series
scores_df['平均'] = mean_series
scores_df['排名'] = rank_series
scores_df

科目  國文  英文   數學   地理  歷史   總分    平均    排名
學號
1   68  67   81   97  82  395  79.0  18.0
2   52  92   71   78  64  357  71.4  37.0
3   63  90   94   71  53  371  74.2  27.0
4   78  99   98   95  80  450  90.0   2.0
5   89  72   55   79  75  370  74.0  28.0
6   78  89   78   95  90  430  86.0   4.0
7   89  73   67   56  76  361  72.2  35.0
8   67  53   64   70  87  341  68.2  42.0
9   88  85   51   98  64  386  77.2  22.0
10  80  82   57   90  56  365  73.0  31.0
11  50  85   91   97  69  392  78.4  19.0
12  64  60   58   61  74  317  63.4  47.0
13  69  72   96   64  72  373  74.6  25.0
14  77  97   79   72  71  396  79.2  16.0
15  77  74   55   74  66  346  69.2  40.0
16  53  72   74   53  59  311  62.2  49.0
17  70  72   51   90  85  368  73.6  30.0
18  80  80   73   93  65  391  78.2  20.0
19  56  64   50   52  54  276  55.2  50.0
20  62  59   62   95  60  338  67.6  44.0
21  76  63   76   89  61  365  73.0  31.0
22  70  94  100   51  93  408  81.6   6.0
23  51  89   75   99  62  376  75.2  23.0
24  91  91   56   82  86  406  81.2   8.0
25  75  74   63   82  61  355  71.0  39.0
26  83  67   51   60  52  313  62.6  48.0
27  72  94   91   86  57  400  80.0  10.0
28  96  53   67   59  50  325  65.0  46.0
29  50  98   88   84  50  370  74.0  28.0
30  88  61   81   80  81  391  78.2  20.0
31  85  63   91   79  81  399  79.8  12.0
32  63  99   79   60  95  396  79.2  16.0
33  96  97   59   59  96  407  81.4   7.0
34  93  94   59   52  60  358  71.6  36.0
35  61  89   83   94  75  402  80.4   9.0
36  99  80   52   76  90  397  79.4  15.0
37  61  82   50   79  60  332  66.4  45.0
38  77  82   55   77  74  365  73.0  31.0
39  66  89   67  100  78  400  80.0  10.0
40  52  94   91   80  81  398  79.6  13.0
41  87  86   93   80  96  442  88.4   3.0
42  77  60   54   87  98  376  75.2  23.0
43  94  51   78   76  74  373  74.6  25.0
44  85  94   52   59  66  356  71.2  38.0
45  77  76   77  100  85  415  83.0   5.0
46  68  67   82   90  58  365  73.0  31.0
47  52  89   77   59  64  341  68.2  42.0
48  73  72   75   93  85  398  79.6  13.0
49  83  56   75   63  68  345  69.0  41.0
50  93  82   98   98  98  469  93.8   1.0

In [29]:
scores_sorted_df = scores_df.sort_values(by='排名',ascending=True)
scores_sorted_df

科目  國文  英文   數學   地理  歷史   總分    平均    排名
學號
50  93  82   98   98  98  469  93.8   1.0
4   78  99   98   95  80  450  90.0   2.0
41  87  86   93   80  96  442  88.4   3.0
6   78  89   78   95  90  430  86.0   4.0
45  77  76   77  100  85  415  83.0   5.0
22  70  94  100   51  93  408  81.6   6.0
33  96  97   59   59  96  407  81.4   7.0
24  91  91   56   82  86  406  81.2   8.0
35  61  89   83   94  75  402  80.4   9.0
27  72  94   91   86  57  400  80.0  10.0
39  66  89   67  100  78  400  80.0  10.0
31  85  63   91   79  81  399  79.8  12.0
48  73  72   75   93  85  398  79.6  13.0
40  52  94   91   80  81  398  79.6  13.0
36  99  80   52   76  90  397  79.4  15.0
14  77  97   79   72  71  396  79.2  16.0
32  63  99   79   60  95  396  79.2  16.0
1   68  67   81   97  82  395  79.0  18.0
11  50  85   91   97  69  392  78.4  19.0
30  88  61   81   80  81  391  78.2  20.0
18  80  80   73   93  65  391  78.2  20.0
9   88  85   51   98  64  386  77.2  22.0
42  77  60   54   87  98  376  75.2  23.0
23  51  89   75   99  62  376  75.2  23.0
13  69  72   96   64  72  373  74.6  25.0
43  94  51   78   76  74  373  74.6  25.0
3   63  90   94   71  53  371  74.2  27.0
29  50  98   88   84  50  370  74.0  28.0
5   89  72   55   79  75  370  74.0  28.0
17  70  72   51   90  85  368  73.6  30.0
10  80  82   57   90  56  365  73.0  31.0
21  76  63   76   89  61  365  73.0  31.0
46  68  67   82   90  58  365  73.0  31.0
38  77  82   55   77  74  365  73.0  31.0
7   89  73   67   56  76  361  72.2  35.0
34  93  94   59   52  60  358  71.6  36.0
2   52  92   71   78  64  357  71.4  37.0
44  85  94   52   59  66  356  71.2  38.0
25  75  74   63   82  61  355  71.0  39.0
15  77  74   55   74  66  346  69.2  40.0
49  83  56   75   63  68  345  69.0  41.0
47  52  89   77   59  64  341  68.2  42.0
8   67  53   64   70  87  341  68.2  42.0
20  62  59   62   95  60  338  67.6  44.0
37  61  82   50   79  60  332  66.4  45.0
28  96  53   67   59  50  325  65.0  46.0
12  64  60   58   61  74  317  63.4  47.0
26  83  67   51   60  52  313  62.6  48.0
16  53  72   74   53  59  311  62.2  49.0
19  56  64   50   52  54  276  55.2  50.0

In [35]:
#班上前5名
scores_sorted_df.iloc[0:5]

科目  國文  英文  數學   地理  歷史   總分    平均   排名
學號
50  93  82  98   98  98  469  93.8  1.0
4   78  99  98   95  80  450  90.0  2.0
41  87  86  93   80  96  442  88.4  3.0
6   78  89  78   95  90  430  86.0  4.0
45  77  76  77  100  85  415  83.0  5.0

In [34]:
#班上後5名
scores_sorted_df.iloc[-5:]

科目  國文  英文  數學  地理  歷史   總分    平均    排名
學號
28  96  53  67  59  50  325  65.0  46.0
12  64  60  58  61  74  317  63.4  47.0
26  83  67  51  60  52  313  62.6  48.0
16  53  72  74  53  59  311  62.2  49.0
19  56  64  50  52  54  276  55.2  50.0